# Generated by Django 2.0.3 on 2018-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='auth_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='token',
            new_name='value',
        ),
        migrations.AddField(
            model_name='auth',
            name='auth_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='auth',
            name='key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户名/手机号/邮箱/'),
        ),
        migrations.AddField(
            model_name='demand',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='demandtype',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
